//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Training
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_tblVehicle
    {
        public int VehicleId { get; set; }
        public string VehicleName { get; set; }
        public string VehicleRegNum { get; set; }
        public string VehicleFleetNum { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual C_tblUser C_tblUser { get; set; }
    }
}
