//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Training
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_tblthread
    {
        public int ThreadId { get; set; }
        public int RequestId { get; set; }
        public System.DateTime Date { get; set; }
        public int RoleId { get; set; }
        public int CommentId { get; set; }
        public bool Status { get; set; }
        public int UnitId { get; set; }
        public Nullable<int> VehicleId { get; set; }
        public int SiteId { get; set; }
    
        public virtual C_tblComment C_tblComment { get; set; }
        public virtual C_tblRequest C_tblRequest { get; set; }
        public virtual C_tblRole C_tblRole { get; set; }
        public virtual C_tblSite C_tblSite { get; set; }
        public virtual C_tblUnit C_tblUnit { get; set; }
    }
}
