//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Training
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DangoteAppEntities : DbContext
    {
        public DangoteAppEntities()
            : base("name=DangoteAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_tblComment> C_tblComment { get; set; }
        public virtual DbSet<C_tblRequest> C_tblRequest { get; set; }
        public virtual DbSet<C_tblRole> C_tblRole { get; set; }
        public virtual DbSet<C_tblSite> C_tblSite { get; set; }
        public virtual DbSet<C_tblthread> C_tblthread { get; set; }
        public virtual DbSet<C_tblUnit> C_tblUnit { get; set; }
        public virtual DbSet<C_tblUser> C_tblUser { get; set; }
        public virtual DbSet<C_tblVehicle> C_tblVehicle { get; set; }
    }
}
